# Generated by Django 4.1.1 on 2022-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0003_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
